### ISSUE TITLE
Authorization returns 401 error while passing bearer token

### ISSUE THREAD

**Issue by YhomiAce** [adonisjs/auth#222] opened 2023-08-31 20:28 UTC
Hi, I'm new to adonisjs, while trying to do authentication and authorization i keep getting stuck at the authorization stage.
Using the geneated token from login endpoint to authorize protected routes using **auth middleware** 

the request returns 401 error
```
"errors": [
        {
            "message": "E_UNAUTHORIZED_ACCESS: Unauthorized access"
        }
    ]
```

This the log of the request I'm making from postman
```
{
  authorization: 'Bearer W29iamVjdCBPYmplY3Rd.C0k2FkyfaWalesRa92Vr-pkIHUc3vEkzRNEMFm3-p_oLg9B8XUBfQfc7qEBP',
  accept: 'application/json',
  'content-type': 'application/json',
  'user-agent': 'PostmanRuntime/7.29.3',
  'postman-token': '022a53d4-0a49-4d18-9ebd-e6feeff4d478',
  host: '127.0.0.1:3333',
  'accept-encoding': 'gzip, deflate, br',
  connection: 'keep-alive'
}
{ guards: [ 'api' ] } // i logged the guards
```
Is their a configuration I might be missing, I've read the doc and I seem to be doing everything as stated

**Comment by RomainLanz** [comment] 2023-09-01 14:09
Hey @YhomiAce!

Could you please create a repository with the minimum amount of code to reproduce your issue?

**Comment by YhomiAce** [comment] 2023-09-04 14:21
> 

sure, here is a link to the repo [Repo](https://github.com/YhomiAce/article_practice)

**Comment by RomainLanz** [comment] 2024-02-15 11:40
Sorry for the delay. This issue has been last in my notification tab. 😅 

I am not sure you still have this issue but I see that you are using an outdated version of `@adonisjs/auth`.
Please upgrade to `^8.2.3`. It should fixed it.

**Comment by RomainLanz** [comment] 2024-03-09 12:31
Closing since no answer from issue reporter.

**Closed by RomainLanz** 2024-03-09 12:31 UTC
