### ISSUE TITLE
Bad loginAs method args type when chained to a guard

### ISSUE THREAD

**Issue by Foohx** [adonisjs/auth#200] opened 2022-05-23 14:59 UTC
In tests, only when chaining `loginAs` to `guard` methods, arguments of `loginAs` method are of type never.

```
(method) loginAs(...args: never): ApiRequest
```

## Package version
**@adonisjs/auth:** `8.2.1`

## Node.js and npm version
**Node.js:** `16.13.0`
**npm:** `8.10.0`

## Sample Code (to reproduce the issue)

Just create a new project with at least `@adonisjs/auth` package, then fill the existing test with the following code :

```ts
const user = await User.create({ email: 'ex@amp.le', password: '123456' })

const response = await client.get('/').loginAs(user) // Everything good

const responseApi = await client.get('/').guard('api').loginAs(user) // <-- Argument of type 'User' is not assignable to parameter of type 'never'


response.assertStatus(200)
responseApi.assertStatus(200)
```

**Comment by thetutlage** [comment] 2022-05-24 04:12
Can you share the `contracts/auth.ts` file?

**Comment by Foohx** [comment] 2022-05-24 07:59
Here is the file:
```ts
import User from 'App/Models/User'

declare module '@ioc:Adonis/Addons/Auth' {
  interface ProvidersList {
    user: {
      implementation: LucidProviderContract<typeof User>
      config: LucidProviderConfig<typeof User>
    }
  }

  interface GuardsList {
    api: {
      implementation: OATGuardContract<'user', 'api'>
      config: OATGuardConfig<'user'>
    }
  }
}
```

**Comment by thetutlage** [comment] 2022-05-24 08:06
Its a bug with the default auth contract template. Lemme push a fix

**Comment by sekistner** [comment] 2022-06-02 09:09
> Its a bug with the default auth contract template. Lemme push a fix

Any hint what the problem is?

**Comment by thetutlage** [comment] 2022-06-15 04:41
You will have to make the changes made in this commit manually.  https://github.com/adonisjs/auth/commit/946e730cdebcfd277cf69ce29d5be40c80a25ce0

The changes will be inside the `contracts/auth.ts` file. New projects will not have this issue

**Closed** 2022-06-15 04:40 UTC
Labels: Type: Bug

**Comment by MANTENN** [comment] 2023-08-17 19:40
@Foohx was guard or loginAs undefined for you when you run the tests?

**Comment by MANTENN** [comment] 2023-08-18 01:21
@Foohx got it, I fixed the type issue—I also had to use the `!` operator for the error to go away. only issue I have is during runtime, the authjs test functions are undefined.

**Comment by Foohx** [comment] 2023-08-18 11:16
@MANTENN Weird that you have to use the `!` operator.

I'm using it without problem like this:
```ts
    const user = await UserFactory.apply('verified').with('roles').create()

    const mock = sinon.mock(ConversationPolicy.prototype)
    mock.expects('before').once().resolves(undefined)
    mock.expects('viewList').once().resolves(true)

    await client.get('/conversations').guard('api').loginAs(user).json({})

    mock.verify()
    mock.restore()
```

But I am not in the latest version for the moment. I'm going to update all deps in the next few days and I'll let you know if I encounter the same problem. :)

**Comment by MANTENN** [comment] 2023-08-18 19:39
@Foohx I used the User.find(1) which either returns a user or null hence why I had to use the `!` operator.

**Comment by MANTENN** [comment] 2023-08-21 16:36
@Foohx turns out I had `NODE_ENV` set to `local` so the bindings never were loaded when I ran my tests. I will need to open a PR to create a warning in the CLI.

**Comment by Foohx** [comment] 2023-08-28 10:01
> @Foohx I used the User.find(1) which either returns a user or null hence why I had to use the `!` operator.

Okay, so everything is normal.
