### ISSUE TITLE
Auth.use().generate connection Issue

### ISSUE THREAD

**Issue by swapnilnandgave** [adonisjs/auth#171] opened 2021-05-15 13:07 UTC
## Package version
node ace --version
App version: 1.0.0
Framework version: 5.1.6
Assembler version: 5.1.1

## Node.js and npm version
node - v14.15.4
npm - v6.14.10

## Sample Code (to reproduce the issue)
I have added new guard with connection `mssql4` but it is taking default env connection instead of mentioned connection defined in guard list

When I try to generate api token using **api4** then it is connecting to default env db connection
`ctx.auth.use('api4').generate`. I have attached below code snippet to better understand.

### auth.ts
```
api4: {
      driver: 'oat',
      tokenProvider: {
        type: 'api',
        driver: 'database',
        table: 'api_tokens',
        foreignKey: 'user_id',
      },

      provider: {
        driver: 'database',
        identifierKey: 'id',
        uids: ['email'],
        usersTable: 'users',
        connection: 'mssql4'
      },
    },
```

### auth.ts in contract

**In interface ProvidersList**
```
dbuser: {
      implementation: DatabaseProviderContract<DatabaseProviderRow>,
      config: DatabaseProviderConfig,
    },
```
**In interface GuardsList**
`api4: {
      implementation: OATGuardContract<'dbuser', 'api'>,
      config: OATGuardConfig<'dbuser'>,
    },`

**Comment by thetutlage** [comment] 2021-05-15 13:18
How do you verify that it is not using the correct connection?

**Comment by swapnilnandgave** [comment] 2021-05-15 17:57
I had verified through below steps
1. Default connection which used is `mysql` Which localhost
2. As you can see in above we have one more connection as `mssql4` which remote server
3. I had stopped localhost connection 
4. When i tried to execute `ctx.auth.use` for `api4` then throwing `failed to connect 127.0.0.1 `

**Comment by thetutlage** [comment] 2021-05-16 01:43
Please share a repo to help reproduce the issue, as it works fine for me.

**Comment by swapnilnandgave** [comment] 2021-05-16 03:01
Can you share your mail ID so I can share project directly to you?

**Comment by thetutlage** [comment] 2021-05-16 06:01
I am looking for a simplified version that can help me reproduce the error. Going through your complete project is not possible for me

**Comment by swapnilnandgave** [comment] 2021-05-16 08:37
Please check below attachment

[NodeAPI-develop.zip](https://github.com/adonisjs/auth/files/6488900/NodeAPI-develop.zip)

**Comment by thetutlage** [comment] 2021-06-02 23:29
Closing since not actionable

**Closed by thetutlage** 2021-06-02 23:29 UTC
